
name: CI
on:
  push:
    branches: [ "main" ]

permissions: 
  id-token: write
  contents: read

jobs:
  build:
    name: CI job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # Build project in next step (dotnet test).
      # - name: Build with dotnet
      #   run: dotnet build --configuration Release

      - name: dotnet tests
        run: dotnet test --configuration Release

      #- name: format
      #  run: dotnet format -v detailed --verify-no-changes
       
      - name: dotnet publish
        run: dotnet publish GithubActions.sln  --configuration Release -o artifacts
        
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/
      
  deploy_dev:
    name: Deploy Dev job
    needs: build
    
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
    secrets: inherit

  deploy_prod:
    name: Deploy Prod job
    needs: deploy_dev
    
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
    secrets: inherit
    