
name: Secrets

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: "./github-actions/github-action.csproj"

jobs:
  secrets:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:  
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"

      - name: echo Github Secrets
        run: echo "The value of ${{ secrets.SECRET_API_KEY }}"
    
  