
name: Secrets

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: "./github-actions/github-action.csproj"

jobs:
  secrets:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:  
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"

      - name: echo Job name
        run: echo "$Job_Name"

  new_job:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:  
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"

      - name: echo Job name
        run: echo "$Job_Name"
        

